/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BayControllerFrame.java
 *
 * Created on Oct 19, 2011, 9:11:11 AM
 */
package app.light_bar;

/**
 *
 * @author gregd
 */
public class LightBarFrame extends javax.swing.JFrame {

    /** Creates new form BayControllerFrame */
    public LightBarFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        light_scroll_pane = new javax.swing.JScrollPane();
        bays_tab_pane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        status_panel = new javax.swing.JPanel();
        message_label = new javax.swing.JLabel();
        last_sent_label = new javax.swing.JLabel();
        last_sent_field = new javax.swing.JTextField();
        last_recv_label = new javax.swing.JLabel();
        last_recv_field = new javax.swing.JTextField();
        menu_bar = new javax.swing.JMenuBar();
        file_menu = new javax.swing.JMenu();
        open_menu_item = new javax.swing.JMenuItem();
        close_menu_item = new javax.swing.JMenuItem();
        save_menu_item = new javax.swing.JMenuItem();
        save_as_menu_item = new javax.swing.JMenuItem();
        file_menu_seperator1 = new javax.swing.JPopupMenu.Separator();
        connect_menu_item = new javax.swing.JMenuItem();
        disconnect_menu_item = new javax.swing.JMenuItem();
        file_menu_seperator2 = new javax.swing.JPopupMenu.Separator();
        exit_menu_item = new javax.swing.JMenuItem();
        configure_menu = new javax.swing.JMenu();
        interface_configure_menu_item = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IPTI Light Bar Interface Simulator");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("light_bar_frame");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        bays_tab_pane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jPanel1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 824, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        bays_tab_pane.addTab("tab1", jPanel1);

        light_scroll_pane.setViewportView(bays_tab_pane);

        jSplitPane1.setRightComponent(light_scroll_pane);

        message_label.setForeground(new java.awt.Color(243, 29, 40));

        last_sent_label.setText("Last Sent:");

        last_sent_field.setEditable(false);
        last_sent_field.setForeground(java.awt.Color.red);
        last_sent_field.setFocusable(false);

        last_recv_label.setText("Recv:");

        last_recv_field.setEditable(false);
        last_recv_field.setForeground(java.awt.Color.red);
        last_recv_field.setFocusable(false);

        javax.swing.GroupLayout status_panelLayout = new javax.swing.GroupLayout(status_panel);
        status_panel.setLayout(status_panelLayout);
        status_panelLayout.setHorizontalGroup(
            status_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(status_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(message_label, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(last_sent_label, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(last_sent_field, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(last_recv_label, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(last_recv_field, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        status_panelLayout.setVerticalGroup(
            status_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(status_panelLayout.createSequentialGroup()
                .addGroup(status_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(message_label)
                    .addComponent(last_sent_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(last_recv_label)
                    .addComponent(last_recv_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(last_sent_label))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(status_panel);

        file_menu.setText("File");

        open_menu_item.setText("Open...");
        file_menu.add(open_menu_item);

        close_menu_item.setText("Close");
        file_menu.add(close_menu_item);

        save_menu_item.setText("Save");
        file_menu.add(save_menu_item);

        save_as_menu_item.setText("Save as...");
        file_menu.add(save_as_menu_item);
        file_menu.add(file_menu_seperator1);

        connect_menu_item.setText("Connect");
        file_menu.add(connect_menu_item);

        disconnect_menu_item.setText("Disconnect");
        file_menu.add(disconnect_menu_item);
        file_menu.add(file_menu_seperator2);

        exit_menu_item.setText("Exit");
        file_menu.add(exit_menu_item);

        menu_bar.add(file_menu);

        configure_menu.setText("Configure");

        interface_configure_menu_item.setText("Interface...");
        configure_menu.add(interface_configure_menu_item);

        menu_bar.add(configure_menu);

        setJMenuBar(menu_bar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleParent(this);

        setBounds(0, 0, 852, 213);
    }// </editor-fold>//GEN-END:initComponents

	private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
		// TODO add your handling code here:
	}//GEN-LAST:event_formWindowClosing

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane bays_tab_pane;
    private javax.swing.JMenuItem close_menu_item;
    private javax.swing.JMenu configure_menu;
    private javax.swing.JMenuItem connect_menu_item;
    private javax.swing.JMenuItem disconnect_menu_item;
    private javax.swing.JMenuItem exit_menu_item;
    private javax.swing.JMenu file_menu;
    private javax.swing.JPopupMenu.Separator file_menu_seperator1;
    private javax.swing.JPopupMenu.Separator file_menu_seperator2;
    private javax.swing.JMenuItem interface_configure_menu_item;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField last_recv_field;
    private javax.swing.JLabel last_recv_label;
    private javax.swing.JTextField last_sent_field;
    private javax.swing.JLabel last_sent_label;
    private javax.swing.JScrollPane light_scroll_pane;
    private javax.swing.JMenuBar menu_bar;
    private javax.swing.JLabel message_label;
    private javax.swing.JMenuItem open_menu_item;
    private javax.swing.JMenuItem save_as_menu_item;
    private javax.swing.JMenuItem save_menu_item;
    private javax.swing.JPanel status_panel;
    // End of variables declaration//GEN-END:variables
    private java.awt.Rectangle frame_bounds;
}
