/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BayControllerFrame.java
 *
 * Created on Oct 19, 2011, 9:11:11 AM
 */
package app.light_bar;

/**
 *
 * @author gregd
 */
public class LightBarFrame extends javax.swing.JFrame {

    /** Creates new form BayControllerFrame */
    public LightBarFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lights_pane = new javax.swing.JScrollPane();
        lights_panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 115));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        lights_pane.setOpaque(false);
        lights_pane.setRequestFocusEnabled(false);

        lights_panel.setAutoscrolls(true);
        lights_panel.setDoubleBuffered(false);
        lights_panel.setLayout(new javax.swing.BoxLayout(lights_panel, javax.swing.BoxLayout.LINE_AXIS));
        lights_pane.setViewportView(lights_panel);

        getContentPane().add(lights_pane);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane lights_pane;
    private javax.swing.JPanel lights_panel;
    // End of variables declaration//GEN-END:variables
}
