/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * D4Module.java
 *
 * Created on Oct 14, 2011, 9:39:33 AM
 */
package app.oc_module;


/**
 *
 * @author gregd
 */
public class OcModulePanel extends javax.swing.JPanel {

    /** Creates new form D4Module */
    public OcModulePanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        upButton = new javax.swing.JButton();
        downButton = new javax.swing.JButton();
        displayText = new javax.swing.JTextField();
        ledButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(235, 231, 45));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(320, 80));
        setMinimumSize(new java.awt.Dimension(320, 80));
        setPreferredSize(new java.awt.Dimension(320, 80));
        setSize(new java.awt.Dimension(320, 80));
        setVerifyInputWhenFocusTarget(false);

        upButton.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        upButton.setAlignmentY(0.0F);
        upButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        upButton.setDoubleBuffered(true);
        upButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        upButton.setLabel("+");
        upButton.setMaximumSize(new java.awt.Dimension(25, 25));
        upButton.setMinimumSize(new java.awt.Dimension(25, 25));
        upButton.setPreferredSize(new java.awt.Dimension(25, 25));

        downButton.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        downButton.setText("-");
        downButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        downButton.setDoubleBuffered(true);
        downButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        downButton.setMaximumSize(new java.awt.Dimension(25, 25));
        downButton.setMinimumSize(new java.awt.Dimension(25, 25));
        downButton.setPreferredSize(new java.awt.Dimension(25, 25));

        displayText.setBackground(java.awt.Color.darkGray);
        displayText.setEditable(false);
        displayText.setFont(new java.awt.Font("Monospaced", 1, 29)); // NOI18N
        displayText.setForeground(java.awt.Color.red);
        displayText.setText("PYRMD OR KG BX");
        displayText.setDoubleBuffered(true);
        displayText.setMaximumSize(new java.awt.Dimension(210, 40));
        displayText.setMinimumSize(new java.awt.Dimension(210, 40));
        displayText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayTextActionPerformed(evt);
            }
        });

        ledButton.setDoubleBuffered(true);
        ledButton.setMaximumSize(new java.awt.Dimension(30, 60));
        ledButton.setMinimumSize(new java.awt.Dimension(30, 60));
        ledButton.setPreferredSize(new java.awt.Dimension(30, 60));
        ledButton.setRequestFocusEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(upButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(downButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(displayText, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ledButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ledButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(displayText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(upButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addComponent(downButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        upButton.getAccessibleContext().setAccessibleName("");
        downButton.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

  private void displayTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayTextActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_displayTextActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField displayText;
    private javax.swing.JButton downButton;
    private javax.swing.JButton ledButton;
    private javax.swing.JButton upButton;
    // End of variables declaration//GEN-END:variables
}
