/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * D4Module.java
 *
 * Created on Oct 14, 2011, 9:39:33 AM
 */
package app.d4_module;

/**
 *
 * @author gregd
 */
public class D4ModulePanel extends javax.swing.JPanel {

    /** Creates new form D4Module */
    public D4ModulePanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addButton = new javax.swing.JButton();
        minusButton = new javax.swing.JButton();
        digitsField = new javax.swing.JTextField();
        javax.swing.JButton ledButton = new javax.swing.JButton();
        upArrowButton = new javax.swing.JButton();
        downArrowButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(210, 208, 206));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setAutoscrolls(true);
        setMaximumSize(new java.awt.Dimension(195, 80));
        setMinimumSize(new java.awt.Dimension(195, 80));
        setPreferredSize(new java.awt.Dimension(195, 80));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addButton.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
        addButton.setAlignmentY(0.0F);
        addButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addButton.setLabel("+");
        addButton.setMaximumSize(new java.awt.Dimension(25, 25));
        addButton.setMinimumSize(new java.awt.Dimension(25, 25));
        addButton.setPreferredSize(new java.awt.Dimension(25, 25));
        add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        addButton.getAccessibleContext().setAccessibleName("Add");

        minusButton.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
        minusButton.setText("-");
        minusButton.setAlignmentY(0.0F);
        minusButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        minusButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        minusButton.setMaximumSize(new java.awt.Dimension(25, 25));
        minusButton.setMinimumSize(new java.awt.Dimension(25, 25));
        minusButton.setPreferredSize(new java.awt.Dimension(25, 25));
        minusButton.setRequestFocusEnabled(false);
        add(minusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        digitsField.setFont(new java.awt.Font("DejaVu Sans", 0, 23));
        digitsField.setText("8888");
        digitsField.setAutoscrolls(true);
        digitsField.setMaximumSize(new java.awt.Dimension(70, 40));
        digitsField.setMinimumSize(new java.awt.Dimension(70, 40));
        digitsField.setPreferredSize(new java.awt.Dimension(70, 40));
        digitsField.setRequestFocusEnabled(false);
        add(digitsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        ledButton.setMaximumSize(new java.awt.Dimension(30, 60));
        ledButton.setMinimumSize(new java.awt.Dimension(30, 60));
        ledButton.setPreferredSize(new java.awt.Dimension(30, 60));
        add(ledButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        upArrowButton.setEnabled(false);
        upArrowButton.setPreferredSize(new java.awt.Dimension(15, 15));
        add(upArrowButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 15, -1, -1));

        downArrowButton.setEnabled(false);
        downArrowButton.setPreferredSize(new java.awt.Dimension(15, 15));
        add(downArrowButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField digitsField;
    private javax.swing.JButton downArrowButton;
    private javax.swing.JButton minusButton;
    private javax.swing.JButton upArrowButton;
    // End of variables declaration//GEN-END:variables
}
