/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * D4Module.java
 *
 * Created on Oct 14, 2011, 9:39:33 AM
 */
package app.d4_module;

/**
 *
 * @author gregd
 */
public class D4ModulePanel extends javax.swing.JPanel {

    /** Creates new form D4Module */
    public D4ModulePanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addButton = new javax.swing.JButton();
        minusButton = new javax.swing.JButton();
        digitsField = new javax.swing.JTextField();
        ledButton = new javax.swing.JButton();
        upArrowButton = new javax.swing.JButton();
        downArrowButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(210, 208, 206));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setAutoscrolls(true);
        setMaximumSize(new java.awt.Dimension(195, 80));
        setMinimumSize(new java.awt.Dimension(195, 80));
        setPreferredSize(new java.awt.Dimension(195, 80));
        setRequestFocusEnabled(false);

        addButton.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        addButton.setAlignmentY(0.0F);
        addButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addButton.setLabel("+");
        addButton.setMaximumSize(new java.awt.Dimension(25, 25));
        addButton.setMinimumSize(new java.awt.Dimension(25, 25));
        addButton.setPreferredSize(new java.awt.Dimension(25, 25));

        minusButton.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        minusButton.setText("-");
        minusButton.setAlignmentY(0.0F);
        minusButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        minusButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        minusButton.setMaximumSize(new java.awt.Dimension(25, 25));
        minusButton.setMinimumSize(new java.awt.Dimension(25, 25));
        minusButton.setPreferredSize(new java.awt.Dimension(25, 25));
        minusButton.setRequestFocusEnabled(false);

        digitsField.setBackground(java.awt.Color.darkGray);
        digitsField.setEditable(false);
        digitsField.setFont(new java.awt.Font("Monospaced", 1, 26)); // NOI18N
        digitsField.setForeground(java.awt.Color.red);
        digitsField.setText("8888");
        digitsField.setMaximumSize(new java.awt.Dimension(70, 40));
        digitsField.setMinimumSize(new java.awt.Dimension(70, 40));
        digitsField.setPreferredSize(new java.awt.Dimension(70, 40));
        digitsField.setRequestFocusEnabled(false);

        ledButton.setMaximumSize(new java.awt.Dimension(30, 60));
        ledButton.setMinimumSize(new java.awt.Dimension(30, 60));
        ledButton.setPreferredSize(new java.awt.Dimension(30, 60));

        upArrowButton.setEnabled(false);
        upArrowButton.setPreferredSize(new java.awt.Dimension(15, 15));
        upArrowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upArrowButtonActionPerformed(evt);
            }
        });

        downArrowButton.setEnabled(false);
        downArrowButton.setPreferredSize(new java.awt.Dimension(15, 15));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minusButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(digitsField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(upArrowButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(downArrowButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(ledButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(minusButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(digitsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(upArrowButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(downArrowButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(ledButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        addButton.getAccessibleContext().setAccessibleName("Add");
    }// </editor-fold>//GEN-END:initComponents

  private void upArrowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upArrowButtonActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_upArrowButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField digitsField;
    private javax.swing.JButton downArrowButton;
    private javax.swing.JButton ledButton;
    private javax.swing.JButton minusButton;
    private javax.swing.JButton upArrowButton;
    // End of variables declaration//GEN-END:variables
}
