/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package app.light_row;

/**
 *
 * @author gregd
 */
public class LightRowPanel extends javax.swing.JPanel {

	/**
	 * Creates new form BayModulePanel
	 */
	public LightRowPanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        light_row_panel = new javax.swing.JPanel();

        setLayout(new java.awt.GridBagLayout());

        light_row_panel.setBackground(new java.awt.Color(0, 0, 0));
        light_row_panel.setForeground(new java.awt.Color(255, 255, 255));
        light_row_panel.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(light_row_panel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel light_row_panel;
    // End of variables declaration//GEN-END:variables
}
