/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package app.light_row;

/**
 *
 * @author gregd
 */
public class LightRowPanel extends javax.swing.JPanel {

	/**
	 * Creates new form BayModulePanel
	 */
	public LightRowPanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        light_group_panel = new javax.swing.JPanel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        light_group_panel.setBackground(new java.awt.Color(0, 0, 0));
        light_group_panel.setForeground(new java.awt.Color(255, 255, 255));
        light_group_panel.setLayout(new java.awt.GridBagLayout());
        add(light_group_panel);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel light_group_panel;
    // End of variables declaration//GEN-END:variables
}
